### ISSUE TITLE
How to import automated tests as manual from the source code

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/docs#107]
if you need to import tests from the source code as manual tests you can assign a specific tag to your tests in code and then set this tag on the Import Project from Source Code page (as shown on a screenshot) and run import command

![CleanShot 2024-08-07 at 12 51 37@2x](https://github.com/user-attachments/assets/116edf6f-2c3d-493e-9eb7-adae70ccc386)

**Comment by TetianaKhomenko** [comment]
https://docs.testomat.io/getting-started/import-tests-from-source-code/

**Comment by maxkryvoshyya** [comment]
URL: https://docs.testomat.io/getting-started/import-tests-from-source-code/#import-automated-tests-as-manual
