### ISSUE TITLE
How to launch Mixed Run

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/docs#111]
We have mixed runs and need to provide a user guide on launching Mixed Runs.
Please note, that it works only with configured CI on a project

![CleanShot 2024-08-08 at 13 52 41@2x](https://github.com/user-attachments/assets/4085d00e-ccc7-4034-9536-892401919a03)

![CleanShot 2024-08-08 at 13 53 28@2x](https://github.com/user-attachments/assets/450553ae-0ad5-4b70-b361-51a994423da2)

**Comment by TetianaKhomenko** [comment]
Run Manual & Automated Tests Combined + link to CI

![CleanShot 2024-08-26 at 19 44 28@2x](https://github.com/user-attachments/assets/fb9900c7-04aa-4cca-8a36-661632b74f65)

**Comment by maxkryvoshyya** [comment]
url: https://docs.testomat.io/getting-started/running-automated-tests/#running-manual-and-automated-tests
