### ISSUE TITLE
Documentation on Test Plans

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/docs#133]
![CleanShot 2024-08-26 at 19 51 48@2x](https://github.com/user-attachments/assets/cb3ef549-9c70-4b3f-bf37-5b835d024b20)

![CleanShot 2024-08-26 at 19 57 05@2x](https://github.com/user-attachments/assets/f6a81605-1a4a-4068-860c-860ef73715e4)

**Comment by TetianaKhomenko** [comment]
mention Plan ID Filter https://docs.testomat.io/reference/reporter/pipes/testomatio/#filter-tests

**Comment by DavertMik** [comment]
```
Test Plans
  Manual
   Select Tests by Checking Tests & Suites
   Select Tests by Tags
   Select Tests by Labels
   Select Tests by QueryLanguage (screenshots + link to query language page)
   Run Automated as Manual
  Automated
   How automated tests are executed on CI (link to CI)
     (or use plan ID with npx start-test-run (mentioned abow)
   Tests need IDs
  Mixed

```

**Comment by maxkryvoshyya** [comment]
url: https://docs.testomat.io/getting-started/test-plans/
