### ISSUE TITLE
Save changes in testeditor

### ISSUE THREAD

**Issue by littlefrontender** [testomatio/docs#38]
**Edit test**
1. Saving changes
2. Saving changes and opening updated test
3. Saving changes and opening parent suite
4. Saving changes and closing all open popovers
5. Closing popover and opening test
6. Closing all open popovers

<img width="1005" alt="Снимок экрана 2023-08-18 в 11 09 41" src="https://github.com/testomatio/docs/assets/79913874/960d2006-5048-4298-98b1-0615df93b74a">

https://docs.testomat.io/getting-started/test-design/

**Comment by TetianaKhomenko** [comment]
done https://docs.testomat.io/getting-started/test-design#how-to-save-your-tests
