### ISSUE TITLE
Add additional info about read-only users, it's free and available for 2 plans

### ISSUE THREAD

**Issue by poliarush** [testomatio/docs#43]
user request:

> Hello
> do you think it's possible to get free read only users in enterprise subscription? 
> asking for developers
> 
> hey, actually we have free read only users for enterprise plans 
> what is the question?
> 
> 
> Цікаво
> ніде не знайшов цієї інформації
> іншими словами в ентерпарйс плані оплачуються тільки юзери з write access?
> 
> так, бачу не додали цю інформацію на сайт
> це ж кілєр фіча

- [ ] Add read-only as role in company, need to mention it's free

https://docs.testomat.io/subscriptions/companies/#roles-within-a-company

- [ ] need to mention read-only users in subscriptions, that's is free and available on pro and enterprise plans

https://docs.testomat.io/subscriptions/subscriptions/

**Comment by TetianaKhomenko** [comment]
done
