### ISSUE TITLE
Java x Testomat guide

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/docs#45]
As we have more and more users using Java for automation. will be good to have a user-friendly explanation for managing Java tests in Testomat.

- Java tests and Artifacts https://testomatio.slack.com/archives/C052D7FPP4L/p1693833374755809
- Java tests matching in Testomat https://testomatio.slack.com/archives/C052D7FPP4L/p1694700175289369
- Java and BDD https://app.crisp.chat/website/4192ab4e-8b76-4b7e-a8c4-ea66dea249e7/inbox/session_6e4db319-d88a-4050-9664-ecb329cbaf61/

**Comment by DavertMik** [comment]
Documented https://docs.testomat.io/reference/reporter/frameworks.html#java-frameworks

**Comment by TetianaKhomenko** [comment]
done
