### ISSUE TITLE
Describe GitHub user permission for Github IMS connections

### ISSUE THREAD

**Issue by poliarush** [testomatio/docs#46]
GitHub Issues Configuration
https://docs.testomat.io/integration/issues-management-systems/#how-to-create-a-defect-for-failed-test

related to https://testomatio.slack.com/archives/C05SAR63CCS/p1694744235053319

**Comment by TetianaKhomenko** [comment]
done https://docs.testomat.io/integration/issues-management-systems/#github-issues-configuration
