### ISSUE TITLE
UI defects in documentation

### ISSUE THREAD

**Issue by TetianaKhomenko** [testomatio/docs#76]
1. Issues widget description is missing  https://docs.testomat.io/usage/analytics/#issues

![CleanShot 2024-05-28 at 21 13 06@2x](https://github.com/testomatio/docs/assets/77803888/637c91bb-a67a-4ba3-8309-a25cd8458d9d)

2. Too big indentations in the list https://docs.testomat.io/usage/continuous-integration/#azure-pipelines

![CleanShot 2024-05-28 at 21 36 37@2x](https://github.com/testomatio/docs/assets/77803888/74c7fd1a-1eed-4537-ae4e-7312c7cacc3a)

3. Please change https://beta.testomat.io/ to https://local.testomat.io/ on page https://docs.testomat.io/reference/import-bdd/

![CleanShot 2024-05-28 at 21 51 54@2x](https://github.com/testomatio/docs/assets/77803888/ba45ee68-74f5-4f9a-b552-79bf92b44f46)

4. Typo in page header https://docs.testomat.io/reference/reporter/env-variables/

![CleanShot 2024-05-28 at 22 24 36@2x](https://github.com/testomatio/docs/assets/77803888/f628831b-d0b2-45aa-a7e1-66d344858f18)

5. Need to improve UI for tables:

https://github.com/testomatio/docs/assets/77803888/864f0999-3dbf-4f35-b8fc-976880e9930e

5.1 TQL Variables table doesn't adjust to the page width https://docs.testomat.io/usage/query-language/#variables. Resizing page doesn't help

![CleanShot 2024-05-28 at 21 46 04@2x](https://github.com/testomatio/docs/assets/77803888/91b3eed2-5ef2-45a9-b510-b9f79ce3584b)

5.2 Compatibility table doesn't adjust to the page width https://docs.testomat.io/reference/reporter/python/#compatibility-table-with-testomatio-check-tests

![CleanShot 2024-05-28 at 22 16 28@2x](https://github.com/testomatio/docs/assets/77803888/c6cb2f67-3b4c-4139-881a-148c3ff8e4a4)

5.3 Variables list table doesn't adjust to the page width https://docs.testomat.io/reference/reporter/env-variables/

![CleanShot 2024-05-28 at 22 23 59@2x](https://github.com/testomatio/docs/assets/77803888/802f0b15-dd72-4ff9-9d48-aa1c01f0700f)

**Comment by DavertMik** [comment]
Everything is fixed on my side excluding 1.

This can be passed to @maxkryvoshyya

**Comment by TetianaKhomenko** [comment]
fixed!

**Comment by maxkryvoshyya** [comment]
url: https://docs.testomat.io/project/analytics/overview/#issues-board
